---

- hosts: localhost
  connection: local
  gather_facts: true

  vars:
    instance_type: t2.micro
    count: 1
    assign_public_ip: yes
    image_name: "ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"
    image_owner: "099720109477"
    wait: yes
    source_dest_check: "no"
    application: natvpn
    owner: bill
    region: "{{ lookup('env', 'AWS_REGION') }}"
    mygroup: "{{ lookup('env', 'MYGROUP') }}"
    keypair: "{{ lookup('env', 'KEYPAIR') }}"
    mysubnet: "{{ lookup('env', 'MYSUBNET') }}"

  roles:
    - { role: ec2-provision-instance, vpc_subnet_id: "subnet-848924cc", group: "{{mygroup}}" }

- name: Configure natvpn instance(s)
  hosts: tag_Name_bastion
  user: ubuntu
  become: yes
  vars:
    region: "{{ lookup('env', 'AWS_REGION') }}"

  pre_tasks:
    - include_vars: "{{playbook_dir}}/group_vars/{{stack_name}}"

  roles:
    - webmin

